LDF_relax_tau: 180.0
control_measures_add_time: 130
cost_lockd: 23.80952380952381
cost_test: 5.0
cost_vacc: 15.0
countries: [Romania, Austria]
default_ICU_beds_per_N: 0.000218
do_ext_analysis: true
do_save_html: false
do_use_plotly: false
end_lockdown_I_thr: 0.99
endtime: 1200
fast_sim: false
fix_elam0_val: 0.02
fix_lam0_val: 0.298
fix_vacc_end_fraction: true
lam0_est_t_limit: 10
lam0_est_t_limit_low: 0
ld_relax_fraction: 0.42857142857142855
ldf_inf_fraction: 0.3
minors_frac: 0.2
new_dbg: false
no_nat_mort_in_model: false
p_test_given_sym: 1.0
plot_I_zoom_win: 180
print_I_hosp_I_sev_I_crit: false
reinfections_based_on_C: true
scen_variant_appear_idx: 15
scen_variant_appear_pi: 1.3
show_MODEL_CHECKS: false
show_VALIDITY: true
sims_in_the_past_tstep: 30
snew_init_pars_est: true
start_lockdown_safety_fac: 2.55
tau_nu: 135.0
tau_nu_vacc: 135.0
time_span: mid
upper_lim_on_r_proj_in_model: true
upper_lim_on_r_proj_in_model_val: 1.0
use_fix_lam0: true
vacc_efficacy: 0.9
vacc_end_fraction: 1.5
vacc_end_fraction_comp: 0.7
var_R_unc_fac: 1.35
